### ISSUE TITLE
Manas - milestone2

### ISSUE THREAD

**Issue by abhii30** [imf-ali/Manas-Frontend#10]
- [x] admissions page UI (Abhi)
- [x] about us page (Abhi)
- [x] Registration number (Ali)
- [x] Admit card page (Ali)
- [x] Blog buttons

MTS Page
- [x] MTS form improvement (Ali/Abhi)
- [x] Student login (Ali)
- [x] Admit Card

**Comment by imf-ali** [comment]
Clsoing this. All task done here
